# fly.toml app configuration file generated for dankimtest-api-black-smoke-8959 on 2025-05-15T18:06:49+01:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'dankimtest-api-black-smoke-8959'
primary_region = 'lhr'

[build]

[http_service]
  internal_port = 4000
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true

[checks]
  [checks.alive]
    type = 'tcp'
    interval = '15s'
    timeout = '2s'
    grace_period = '5s'

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1
